#!/usr/bin/env node

import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const PACKAGE_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const GENERATED_ARTIFACT = path.join(PACKAGE_ROOT, "src", "artifact.generated.mjs");
// The only network origin in the document CSP. Kept as a literal
// (not imported from integration.mjs, which asserts against the artifact this
// script regenerates); scripts/validate.mjs cross-checks all three copies.
const PEARL_IMAGE_ORIGIN = "https://agent.joinpearl.co";

function inlineModel(source) {
  return source
    .replace(/^export function /gm, "function ")
    .replace(/^export const /gm, "const ");
}

function inlineApp(source) {
  return source.replace(/^import \{ normalizeToolResult, recoveryPrompt \} from "\.\/model\.mjs";\n/, "");
}

function assertEmbeddable(label, source) {
  if (/<\/script/i.test(source) || /<\/style/i.test(source)) {
    throw new Error(`${label} contains a closing tag and cannot be safely inlined`);
  }
}

export async function buildHtml() {
  const [styles, modelSource, appSource] = await Promise.all([
    readFile(path.join(PACKAGE_ROOT, "src", "styles.css"), "utf8"),
    readFile(path.join(PACKAGE_ROOT, "src", "model.mjs"), "utf8"),
    readFile(path.join(PACKAGE_ROOT, "src", "app.mjs"), "utf8"),
  ]);
  assertEmbeddable("styles.css", styles);
  assertEmbeddable("model.mjs", modelSource);
  assertEmbeddable("app.mjs", appSource);
  const script = `${inlineModel(modelSource)}\n${inlineApp(appSource)}`;
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
  <meta name="color-scheme" content="light dark">
  <meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; img-src data: ${PEARL_IMAGE_ORIGIN}; connect-src 'none'; font-src 'none'; media-src 'none'; frame-src 'none'; object-src 'none'; worker-src 'none'; base-uri 'none'; form-action 'none'">
  <title>Pearl Concierge</title>
  <style>${styles}</style>
</head>
<body>
  <main id="app" class="app-shell" aria-label="Pearl results"></main>
  <p id="live-status" class="sr-only" role="status" aria-live="polite" aria-atomic="true"></p>
  <script type="module">${script}</script>
</body>
</html>
`;
}

export function digestHtml(html) {
  return createHash("sha256").update(html).digest("hex");
}

export function buildArtifactModule(html) {
  const bytes = Buffer.byteLength(html);
  const digest = digestHtml(html);
  return `// Generated by scripts/build.mjs --write-artifact. Do not edit by hand.\n`
    + `export const PEARL_MCP_APP_ARTIFACT_BYTES = ${bytes};\n`
    + `export const PEARL_MCP_APP_ARTIFACT_SHA256 = ${JSON.stringify(digest)};\n`
    + `export const PEARL_MCP_APP_ARTIFACT_HTML = ${JSON.stringify(html)};\n`;
}

async function main() {
  const args = process.argv.slice(2);
  const outIndex = args.indexOf("--out");
  if (outIndex >= 0 && !args[outIndex + 1]) throw new Error("--out requires a file path");
  const writeArtifact = args.includes("--write-artifact");
  if (writeArtifact && outIndex >= 0) throw new Error("--write-artifact and --out are mutually exclusive");
  const unknown = args.filter((arg, index) => arg !== "--out" && arg !== "--write-artifact" && index !== outIndex + 1);
  if (unknown.length) throw new Error(`Unknown argument: ${unknown[0]}`);
  const html = await buildHtml();
  const digest = digestHtml(html);
  if (writeArtifact) {
    await writeFile(GENERATED_ARTIFACT, buildArtifactModule(html), "utf8");
    console.log(`Generated ${GENERATED_ARTIFACT} (${Buffer.byteLength(html)} HTML bytes, sha256 ${digest})`);
  } else if (outIndex >= 0) {
    const target = path.resolve(args[outIndex + 1]);
    await mkdir(path.dirname(target), { recursive: true });
    await writeFile(target, html, "utf8");
    console.log(`Built ${target} (${Buffer.byteLength(html)} bytes, sha256 ${digest})`);
  } else {
    console.log(`Pearl MCP App build is deterministic (${Buffer.byteLength(html)} bytes, sha256 ${digest})`);
  }
}

if (process.argv[1] === fileURLToPath(import.meta.url)) await main();
